version: '3.8'

services:
  front-end:
    build:
      context: ./celestial-application
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_AUTH_URL=http://localhost:5000/
      - NEXT_PUBLIC_API_CHAT_URL=http://localhost:8000/
      - NEXTAUTH_SECRET=KCMK2JWgOOkAQ4
    depends_on:
      - auth
      - chat

  auth:
    build:
      context: ./celestial-webservices/auth
    ports:
      - "5000:5000"
    environment:
      - DB_CONNECTION_STRING=mongodb+srv://admin:LDumKeXcV3zhQaf583DPstCXFw5khF2qXrf2a6LDph@celestial.ijfhzun.mongodb.net/
      - JWT_SECRET=Bku85iuWzza57CUu6w93EKYs1Oh1IpyxLiqpzHU6kI9XDxA2duqqN7sWhmwU5
      - JWT_EXPIRATION_TIME=120m
      - API_AUTH_URL=http://localhost:5000
      - API_CHAT_URL=http://localhost:8000

  chat:
    build:
      context: ./celestial-webservices/chat
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION_STRING=mongodb+srv://admin:LDumKeXcV3zhQaf583DPstCXFw5khF2qXrf2a6LDph@celestial.ijfhzun.mongodb.net/
      - JWT_SECRET=Bku85iuWzza57CUu6w93EKYs1Oh1IpyxLiqpzHU6kI9XDxA2duqqN7sWhmwU5
      - JWT_EXPIRATION_TIME=120m
      - API_AUTH_URL=http://localhost:5000
      - API_CHAT_URL=http://localhost:8000
